### ISSUE TITLE
Add a Chocolatey shim for doublecmd?

### ISSUE THREAD

**Issue by 29039** [marcinbojko/doublecmd#2]
I often use WINKEY+R to launch programs quickly.

For example, I can press WINKEY+R > explorer > [ENTER] to get explorer up right away.

I want to do the same with Double Commander.

Can you please add a Chocolatey shim so that I can do this.

Thanks!

**Comment by marcinbojko** [comment]
Thank's I'll give it a try.

**Comment by marcinbojko** [comment]
Unfortunately, doublecmd is not a single binary file - it depends on myriads of different small files to start. In your case, I'd recommend adding doublecmd's location to the PATH variable.

**Comment by 29039** [comment]
> Unfortunately, doublecmd is not a single binary file - it depends on myriads of different small files to start. In your case, I'd recommend adding doublecmd's location to the PATH variable.

[WinScp](https://community.chocolatey.org/packages/winscp.install/6.1.2#files) does a similar thing if you want to check out their chocolatey package.

It uses Install-BinFile and Register-Application to achieve it

Just needs to point to the doublecmd.exe

This bit looks like it should do the trick:
`$packageName = $packageArgs.packageName`
`$installLocation = Get-AppInstallLocation "$packageName*"`
`if (!$installLocation)  { Write-Warning "Can't find $packageName install location"; return }`
`Write-Host "$packageName installed to '$installLocation'"`

`Install-BinFile $packageName "$installLocation\$packageName.exe"`
`Register-Application "$installLocation\$packageName.exe"`
